#!/bin/sh
### BEGIN INIT INFO
# Provides:          mailpit
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts mailpit email smtp server
# Description:       starts mailpit using start-stop-daemon
### END INIT INFO

DESC="Mailpit email smtp server"
NAME=mailpit
DAEMON=$(which mailpit)

test -x $DAEMON || exit 0

PIDFILE=/var/run/$NAME.pid

# Set the ulimits
ulimit -n 8192

start() {
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON
}

stop() {
    echo "Unstoppable process"
}

status() {
    if [ -f $PIDFILE ]; then
        if kill -0 $(cat "$PIDFILE"); then
            echo "$NAME is running"
        else
            echo "$NAME process is dead, but pidfile exists"
        fi
    else
        echo "$NAME is not running"
    fi
}

case "$1" in
    start)
        echo "Starting $NAME"
        start
    ;;
    stop)
        echo "Stopping $NAME"
        stop
    ;;
    restart)
        echo "Restarting $NAME"
        stop
        start
    ;;
    status)
        status
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 2
    ;;
esac

exit 0
